### ISSUE TITLE
Incorrect Designation validation for Person

### ISSUE THREAD

**Issue by jieliangang** [CS2113-AY1819S1-T16-2/main#126]
This affects the following commands

- add
- edit
- login

The current validation of designation is wrong, leading to user being able to enter incorrect designation when adding or editing person. Then, the person cannot login due to the incorrect place of designation validation (which is currently at login command). 

This can be fixed by having a stricter validation at the isValidDesignation under the Designation class.

**Comment by Jeevz10** [comment]
Fixed
